### ISSUE TITLE
DSN / Better Rolls Incompatibility

### ISSUE THREAD

**Issue by jenthura** [crash1115/blind-roll-skills#10]
When using the Dice So Nice module, the players can read their roll on the 3D dice, even though the result is hidden in the chat.

**Comment by crash1115** [comment]
Hi there! What version of dnd5e and Foundry are you running, and are you using any other modules that change how rolls work (better rolls, mess, etc)?

**Comment by jenthura** [comment]
DND5e version 0.98, Foundry version 0.6.6. I can recreate this error consistently with only your module, Dice so Nice(v2.0.4) and Better Rolls 5e (v1.1.11).

**Comment by crash1115** [comment]
Ah. Yeah, that'd do it. Currently the module doesn't work when using Dice So Nice in conjunction with Better Rolls. 

It's unfortunate, but it's due to the way that BR modifies the way that rolling works; there's no point in the BR roll process that I can hook into to tell it to shut Dice So Nice animations off. The good news is that it seems like the creator of BR is working on [some changes](https://github.com/RedReign/FoundryVTT-BetterRolls5e/issues/131) that may make this a possibility in the near future. I'm not sure when that'll be, but if/when it gets done, I'll get a fix for this out! 

If you're on the Foundry discord server and drop me a message on there, I can make sure to ping you when that happens. Otherwise I'm just going to leave this issue open until I can get everything fixed and you should be notified that way. 👍

**Comment by jenthura** [comment]
Thank, I appreciate that greatly! I'll be sure to check in on discord.

**Comment by crash1115** [comment]
Should have a fix for this in the next release (sometime this evening, probably). It's only been tested on the alpha version of BR, so make sure you're using that.
