### ISSUE TITLE
Telling the players that a roll has been made

### ISSUE THREAD

**Issue by millieloop** [crash1115/blind-roll-skills#14]
Love the mod! - But one minor issue for my game at least is that the players don't know if their 'hidden roll' has actually rolled. - There is no prompt or message to the player to say that it's worked.

Obviously I can call out "Thanks, I got it", but it would be lovely if a little message popped up for the player saying "Thanks", or "XXX Skill check rolled".

Cheers

**Comment by crash1115** [comment]
For anyone who ends up reading this down the line, the issue reporter and I spoke on Discord...

This issue occurs when using Blind Roll Skills in conjunction with Midi-QOL. There's currently an issue with midi where it hides blind rolls even when the setting to do so is disabled. I've filed a bug report (which you can find [here](https://gitlab.com/tposney/midi-qol/-/issues/195)). If that turns out to be the issue here, then I'll mark this closed.

**Comment by crash1115** [comment]
This got fixed a few days ago in midi 0.3.50. Marking this as closed.
