### ISSUE TITLE
[Feature] Adding support for hidden initiative rolls

### ISSUE THREAD

**Issue by tagnullde** [crash1115/blind-roll-skills#16]
Initiative isn't a skill per se, but it might be a nice addition to have those hidden aswell.

Thank you very much!

**Comment by crash1115** [comment]
I don't know off hand how easy/hard this will be to implement, but I can definitely take a look into it. Thanks for the suggestion!

**Comment by crash1115** [comment]
This is probably something I can implement, but it'll come with a caveat: I can hide the rolls, both in chat and on 3d dice, but hiding the results on the combat tracker is out of scope for this project. That should mirror the functionality in core as if you'd had them make the roll with Blind GM Roll selected.

Is that good enough?

**Comment by tagnullde** [comment]
I appriciate the effort. However, if you would replicate core functionality, wouldn't that be like "wasted effort" on your end?
I don't want you spent hours on something that would greatly improve the module for a lot of folks.

That being said: It would certainly be enough if you think it would be a useful addition for everyone. ;)
Otherwise it would be just fine if you do other great things. ;D

Thanks mate!

**Comment by crash1115** [comment]
Ah, it's only a couple lines of code, so no worries there! I'm not sure I'd consider it wasted effort either. Ultimately the entire module is just a collection of things that can be done in core - I'm just giving users shortcuts so there's less of a barrier to stay consistent.

I'll add it in, since it's not a ton of work. If it even makes one person's game a little smoother, then that's worthwhile as far as I'm concerned. I'll shoot for this weekend sometime.

And thank _you_ for taking the time to leave feedback. It's so very appreciated. 😄

**Comment by tagnullde** [comment]
You are most welcome. :)
