### ISSUE TITLE
Disable help cards for world instead of just per client

### ISSUE THREAD

**Issue by flamewave000** [crash1115/blind-roll-skills#26]
I'm just starting with this module. My players and I have already been playing with blind rolling, but sometimes a player forgets to switch their roll type, so this module will be a really great addition. One of my issues is that it displays a "Help" card for every single roll that the players make. Two options I thought were as follows:

1. Change the Help Card setting to World scope.
2. Add a button to the Help Card that says "Don't show again" and when clicked, changes that client setting.

**Comment by crash1115** [comment]
Hey, thanks for reaching out! Just so I can get a better sense of your problem here...

1. When you say  "every single roll," are they also displaying when rolls are made that you haven't specified should be blind?

2. Are you as a GM seeing the messages when the player rolls?

Trying to understand if this is a case of something being broken (yes to either of the above would indicate this is true), or if you have an unusual use case where you want everything to be blind all the time and are just annoyed by the help messages (and reasonably so).

**Comment by flamewave000** [comment]
No bugs, working as designed. This is just an enhancement request.

We use blind rolls for anything RP or Combat related. Sometimes my players have difficulty finding the correct settings to turn things on or off. These Help Cards are rather large, and they likely won't need them. It would be nice to either have a way for me as the DM to disable them for everyone, or for the card to have a button in its layout that can be clicked to disable them.

**Comment by crash1115** [comment]
Understood!

I'm personally not keen on allowing a GM to override client settings that exist for accessibility reasons. The messages came from a series of requests from users who wanted to know why an expected behavior was being changed, and such things can be stressful for some folks.

I can definitely see about putting a button in the card, though. That's good UX, and an oversight on my part in the first place.

**Comment by flamewave000** [comment]
Yeah the button on the card would be perfect 👍🏽

**Comment by Shuggaloaf** [comment]
Would like to 2nd this request. Players and myself love the mod, but all players found the chat cards annoying after the 1st notification and disabled them.  

I know you mentioned above that some people were upset by the unexpected change but I think having the message displayed just once still solves that issue. Having a checkbox in the 1st help chat message would be much easier for players who don't want it but still gives the choice to those who may want it. Good solution. 

Thanks for this very helpful mod!!

**Comment by crash1115** [comment]
Released in 0.8.0
